"""Backward-compat shim — canonical location is tools/registry.py and tools/builtin/browser.py."""

from tools.registry import ToolRegistry, SmolhandTools
from tools.builtin.browser import (
    get_navigation_stack,
    get_DOM_Tree,
    get_browser_snapshot,
    analyze_visual_context,
    explore_dom_with_astar,
    score_task_progress_q_learning,
    set_browser_url,
    create_new_tab,
    switch_to_tab,
    close_tab,
    list_open_tabs,
    find_path_to_target,
    get_address,
    get_geolocation,
    quit_browser,
    think,
    search_item_ctrl_f,
    go_back,
    close_popups,
)

__all__ = [
    "ToolRegistry",
    "SmolhandTools",
    "get_navigation_stack",
    "get_DOM_Tree",
    "get_browser_snapshot",
    "analyze_visual_context",
    "explore_dom_with_astar",
    "score_task_progress_q_learning",
    "set_browser_url",
    "create_new_tab",
    "switch_to_tab",
    "close_tab",
    "list_open_tabs",
    "find_path_to_target",
    "get_address",
    "get_geolocation",
    "quit_browser",
    "think",
    "search_item_ctrl_f",
    "go_back",
    "close_popups",
]
