"""Event sourcing for cognitive system.

This module provides:
- Event types for all state changes
- Event store with persistence
- State reconstruction from events (fold/replay)
- CQRS patterns
"""

from __future__ import annotations

import json
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, TypeVar

from smolclaw.cognitive.effects import Event, EventStream


# =============================================================================
# Cognitive System Events
# =============================================================================

@dataclass
class IntentReceivedEvent(Event):
    """Event: User intent received."""
    intent: str = ""
    session_id: str = ""
    source: str = "cli"
    
    def __post_init__(self):
        self.event_type = "intent_received"
        self.timestamp = self.timestamp or time.time()
        self.event_id = self.event_id or str(uuid.uuid4())
        self.metadata = {
            "intent": self.intent,
            "session_id": self.session_id,
            "source": self.source,
        }


@dataclass
class PlanGeneratedEvent(Event):
    """Event: Plan generated by planner."""
    plan: Dict[str, Any] = field(default_factory=dict)
    strategy: str = ""
    confidence: float = 0.0
    
    def __post_init__(self):
        self.event_type = "plan_generated generated
        self.timestamp = self.timestamp or time.time()
        self.event_id = self.event_id or str(uuid.uuid4())
        self.metadata = {
            "plan": self.plan,
            "strategy": self.strategy,
            "confidence": self.confidence,
        }


@dataclass
class ToolExecutedEvent(Event):
    """Event: Tool executed."""
    tool_name: str = ""
    arguments: Dict[str, Any] = field(default_factory=dict)
    result: str = ""
    success: bool = True
    
    def __post_init__(self):
        self.event_type = "tool_executed"
        self.timestamp = self.timestamp or time.time()
        self.event_id = self.event_id or str(uuid.uuid4())
        self.metadata = {
            "tool_name": self.tool_name,
            "arguments": self.arguments,
            "result": self.result,
            "success": self.success,
        }


@dataclass
class NavigationEvent(Event):
    """Event: Navigation occurred."""
    from_url: str = ""
    to_url: str = ""
    action: str = ""
    
    def __post_init__(self):
        self.event_type = "navigation"
        self.timestamp = self.timestamp or time.time()
        self.event_id = self.event_id or str(uuid.uuid4())
        self.metadata = {
            "from_url": self.from_url,
            "to_url": self.to_url,
            "action": self.action,
        }


@dataclass
class StateTransitionEvent(Event):
    """Event: DFA state transition."""
    from_state: str = ""
    to_state: str = ""
    trigger_event: str = ""
    
    def __post_init__(self):
        self.event_type = "state_transition"
        self.timestamp = self.timestamp or time.time()
        self.event_id = self.event_id or str(uuid.uuid4())
        self.metadata = {
            "from_state": self.from_state,
            "to_state": self.to_state,
            "trigger_event": self.trigger_event,
        }


@dataclass
class TaskCompletedEvent(Event):
    """Event: Task completed."""
    result: str = ""
    success: bool = True
    duration_seconds: float = 0.0
    
    def __post_init__(self):
        self.event_type = "task_completed"
        self.timestamp = self.timestamp or time.time()
        self.event_id = self.event_id or str(uuid.uuid4())
        self.metadata = {
            "result": self.result,
            "success": self.success,
            "duration_seconds": self.duration_seconds,
        }


@dataclass
class ErrorEvent(Event):
    """Event: Error occurred."""
    error_message: str = ""
    stack_trace: str = ""
    recoverable: bool = True
    
    def __post_init__(self):
        self.event_type = "error"
        self.timestamp = self.timestamp or time.time()
        self.event_id = self.event_id or str(uuid.uuid4())
        self.metadata = {
            "error_message": self.error_message,
            "stack_trace": self.stack_trace,
            "recoverable": self.recoverable,
        }


# =============================================================================
# Event Store
# =============================================================================

class EventStore:
    """Immutable event store for cognitive system.
    
    Features:
    - Append-only (immutable)
    - Event replay
    - State reconstruction (fold)
    - Version tracking
    - Optional persistence
    """
    
    def __init__(self, persistence_path: Optional[str] = None):
        """Initialize event store.
        
        Args:
            persistence_path: Optional path for event persistence
        """
        self.events: List[Event] = []
        self.persistence_path = Path(persistence_path) if persistence_path else None
        self._version = 0
        
        # Load existing events if persistence enabled
        if self.persistence_path and self.persistence_path.exists():
            self._load_events()
    
    def append(self, event: Event) -> int:
        """Append event to store (immutable - returns new version).
        
        Args:
            event: Event to append
            
        Returns:
            New version number
        """
        self.events.append(event)
        self._version += 1
        
        # Persist if enabled
        if self.persistence_path:
            self._persist_event(event)
        
        return self._version
    
    def append_many(self, events: List[Event]) -> int:
        """Append multiple events.
        
        Args:
            events: Events to append
            
        Returns:
            New version number
        """
        for event in events:
            self.append(event)
        return self._version
    
    def get_events(self, from_version: int = 0) -> EventStream:
        """Get events from version onwards.
        
        Args:
            from_version: Starting version
            
        Returns:
            EventStream with events
        """
        return EventStream(events=self.events[from_version:])
    
    def get_events_by_type(self, event_type: str) -> EventStream:
        """Get events of specific type.
        
        Args:
            event_type: Event type to filter
            
        Returns:
            EventStream with filtered events
        """
        filtered = [e for e in self.events if e.event_type == event_type]
        return EventStream(events=filtered)
    
    def fold[T](
        self,
        initial: T,
        reducer: Callable[[T, Event], T]
    ) -> T:
        """Fold events into single value (state reconstruction).
        
        Args:
            initial: Initial accumulator value
            reducer: Function (acc, event) -> new_acc
            
        Returns:
            Final accumulated value
        """
        acc = initial
        for event in self.events:
            acc = reducer(acc, event)
        return acc
    
    def replay(self, from_version: int = 0) -> EventStream:
        """Replay events from version.
        
        Args:
            from_version: Starting version
            
        Returns:
            EventStream for replay
        """
        return self.get_events(from_version)
    
    def get_version(self) -> int:
        """Get current store version.
        
        Returns:
            Version number
        """
        return self._version
    
    def __len__(self) -> int:
        return len(self.events)
    
    # Private persistence methods
    
    def _persist_event(self, event: Event) -> None:
        """Persist single event to file."""
        if not self.persistence_path:
            return
        
        events_file = self.persistence_path / "events.jsonl"
        with open(events_file, "a", encoding="utf-8") as f:
            f.write(json.dumps(event.to_dict()) + "\n")
    
    def _load_events(self) -> None:
        """Load events from file."""
        if not self.persistence_path:
            return
        
        events_file = self.persistence_path / "events.jsonl"
        if not events_file.exists():
            return
        
        with open(events_file, "r", encoding="utf-8") as f:
            for line in f:
                event_dict = json.loads(line.strip())
                event = self._deserialize_event(event_dict)
                if event:
                    self.events.append(event)
                    self._version += 1
    
    def _deserialize_event(self, event_dict: dict) -> Optional[Event]:
        """Deserialize event from dictionary."""
        event_type = event_dict.get("event_type")
        
        if event_type == "intent_received":
            return IntentReceivedEvent(
                intent=event_dict["metadata"].get("intent", ""),
                session_id=event_dict["metadata"].get("session_id", ""),
                source=event_dict["metadata"].get("source", "cli"),
                event_id=event_dict.get("event_id"),
                timestamp=event_dict.get("timestamp"),
            )
        elif event_type == "plan_generated
            return PlanGeneratedEvent(
                plan=event_dict["metadata"].get("plan", {}),
                strategy=event_dict["metadata"].get("strategy", ""),
                confidence=event_dict["metadata"].get("confidence", 0.0),
                event_id=event_dict.get("event_id"),
                timestamp=event_dict.get("timestamp"),
            )
        elif event_type == "tool_executed":
            return ToolExecutedEvent(
                tool_name=event_dict["metadata"].get("tool_name", ""),
                arguments=event_dict["metadata"].get("arguments", {}),
                result=event_dict["metadata"].get("result", ""),
                success=event_dict["metadata"].get("success", True),
                event_id=event_dict.get("event_id"),
                timestamp=event_dict.get("timestamp"),
            )
        # Add more event types as needed
        
        # Fallback to base Event
        return Event(
            event_id=event_dict.get("event_id"),
            event_type=event_type,
            timestamp=event_dict.get("timestamp"),
            metadata=event_dict.get("metadata", {}),
        )


# =============================================================================
# CQRS: Command and Query Separation
# =============================================================================

T = TypeVar('T')

class Command:
    """Base class for commands (write operations)."""
    pass


class Query:
    """Base class for queries (read operations)."""
    pass


@dataclass
class ExecuteToolCommand(Command):
    """Command: Execute a tool."""
    tool_name: str
    arguments: Dict[str, Any]


@dataclass
class NavigateCommand(Command):
    """Command: Navigate to URL."""
    url: str
    action: str = "goto"


@dataclass
class GetStateQuery(Query):
    """Query: Get current state."""
    pass


@dataclass
class GetEventHistoryQuery(Query):
    """Query: Get event history."""
    from_version: int = 0


class CognitiveSystemStore:
    """CQRS store for cognitive system.
    
    Separates write (command) and read (query) models.
    """
    
    def __init__(self, event_store: EventStore):
        """Initialize CQRS store.
        
        Args:
            event_store: Event store to use
        """
        self.event_store = event_store
        self.read_model: Dict[str, Any] = {
            "current_state": "await_intent",
            "current_goal": "",
            "executed_tools": [],
            "navigation_history": [],
            "errors": [],
        }
        
        # Build read model from events
        self._rebuild_read_model()
    
    def execute(self, command: Command) -> None:
        """Execute command (write side).
        
        Args:
            command: Command to execute
        """
        if isinstance(command, ExecuteToolCommand):
            event = ToolExecutedEvent(
                tool_name=command.tool_name,
                arguments=command.arguments,
                result="",  # Would be filled after execution
                success=True,
            )
            self.event_store.append(event)
        
        elif isinstance(command, NavigateCommand):
            event = NavigationEvent(
                from_url=self.read_model.get("current_url", ""),
                to_url=command.url,
                action=command.action,
            )
            self.event_store.append(event)
        
        # Update read model
        self._rebuild_read_model()
    
    def ask(self, query: Query) -> Any:
        """Ask query (read side).
        
        Args:
            query: Query to execute
            
        Returns:
            Query result
        """
        if isinstance(query, GetStateQuery):
            return self.read_model.copy()
        
        elif isinstance(query, GetEventHistoryQuery):
            return self.event_store.get_events(query.from_version)
        
        return None
    
    def _rebuild_read_model(self) -> None:
        """Rebuild read model from events (projection)."""
        def projector(state: Dict[str, Any], event: Event) -> Dict[str, Any]:
            if event.event_type == "intent_received":
                state["current_goal"] = event.metadata.get("intent", "")
            
            elif event.event_type == "tool_executed":
                state["executed_tools"].append({
                    "name": event.metadata.get("tool_name"),
                    "success": event.metadata.get("success"),
                })
            
            elif event.event_type == "navigation":
                state["navigation_history"].append({
                    "from": event.metadata.get("from_url"),
                    "to": event.metadata.get("to_url"),
                })
                state["current_url"] = event.metadata.get("to_url")
            
            elif event.event_type == "error":
                state["errors"].append(event.metadata.get("error_message"))
            
            elif event.event_type == "task_completed":
                state["current_goal"] = ""
                state["current_state"] = "done"
            
            return state
        
        self.read_model = self.event_store.fold(
            {
                "current_state": "await_intent",
                "current_goal": "",
                "current_url": "",
                "executed_tools": [],
                "navigation_history": [],
                "errors": [],
            },
            projector,
        )


__all__ = [
    # Events
    "IntentReceivedEvent",
    "PlanGeneratedEvent",
    "ToolExecutedEvent",
    "NavigationEvent",
    "StateTransitionEvent",
    "TaskCompletedEvent",
    "ErrorEvent",
    # Event Store
    "EventStore",
    # CQRS
    "Command",
    "Query",
    "ExecuteToolCommand",
    "NavigateCommand",
    "GetStateQuery",
    "GetEventHistoryQuery",
    "CognitiveSystemStore",
]
